# name属性用来指定这个工作流的名字
name: Daily-Wechat-Push

# 这个部分用来指定能够触发工作流执行的事件
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * *'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Working
      run: |
        echo Hello World
      
